<a href="https://colab.research.google.com/github/shres14/xyz/blob/main/linearreg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd 

In [2]:
df = pd.read_csv("LSM1.csv")

In [3]:
df

X  Y
0  1  2
1  2  4
2  3  5
3  4  4
4  5  5

In [13]:
x = df.iloc[:,0].values.reshape(5,1)
y = df.iloc[:,1].values

In [14]:
x.shape

(5, 1)

In [5]:
x

array([1, 2, 3, 4, 5])

In [6]:
y

array([2, 4, 5, 4, 5])

In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
Lin = LinearRegression()

In [15]:
Lin.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [16]:
Lin.predict([[2.5]])

array([3.7])